# Label term windows and panes
set -g pane-border-format "#{session_name}:#{window_index}.#{pane_index}"
set -g pane-border-status top

# Set terminal
set -g default-terminal 'screen-256color'

# Allow 24-bit colors to work in Alacritty terminal
set -ga terminal-overrides ',*256col*:Tc'

# Update these environment variables when attaching
set-option -g update-environment "SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

# Unbind the double-prefix (prevent accidental last-window switch) and learn to not be in a nested tmux session
unbind C-b
bind C-b send-prefix

# Needed for vim yank to system clipboard with OSC52
set-option -g set-clipboard on

# Neovim suggested an escape time of 10 ms (time between a real human typing esc vs
# the system sending an esc character in front of other control characters)
set-option -sg escape-time 10


# Select panes using vim shortcuts
setw -g mode-keys vi
bind-key -r \; last-window
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# Select windows left and right using Ctl-h or Ctl-l
# bind-key -r C-h select-window -t :-
# bind-key -r C-l select-window -t :+

# Allow repeat pressing to move to next/prev window
bind-key -r n next-window
bind-key -r p previous-window

# Allows for scrolling
# https://superuser.com/questions/209437/how-do-i-scroll-in-tmux
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"


# Start window numbers at 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Do not allow tmux to change manually named windows
set-option -g allow-rename off

# Renumber windows sequentially after closing any of them
set -g renumber-windows on


# increase scrollback lines
#set -g history-limit 10000

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Reload tmux config
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded..."
# Send focus events to vim/nvim
set -g focus-events on


# This should allow use of copy/paste from macOS
# Requires: brew install reattach-to-user-namespace
# set-option -g default-command "reattach-to-user-namespace -l $SHELL"

# Status bar (session name, hostname, time)
set -g status-left ''
set -g status-right ''


# Colors:
# 231m == "light grey" working dir text color
# 197m == "red" working dir background color #fc004d
# 000000 black
# CFD8DC rgb(207,216,220) (slate) light gray
# #1d1f21 very dark, almost black
# d0d0d0 light gray
# 27m == "blue" working dir background color
# 1F51FF royal blue

# status bar
set -g status-style 'bg=#1F51FF fg=#FFFFFF'

# currently active tab
setw -g window-status-current-style 'fg=#000000 bg=#d0d0d0 bold'
setw -g window-status-current-format ' #I#[fg=#000000]:#[fg=#000000]#W#[fg=#000000]#F '


# Change word separators so double clicking highlights entire path
# Use these characters as separators: space, quotes, colon
set-option -g word-separators ' ":,;'
